name: Build

on: [push, pull_request]

env:
  APP_NAME: throughput_app

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.APP_NAME }}

      - name: Initialize
        working-directory: ${{ env.APP_NAME }}
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt
      - name: Build firmware
        working-directory: ${{ env.APP_NAME }}
        run: |
          west build -b nrf5340dk_nrf5340_cpuapp --pristine app
      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: example-application/build/zephyr/zephyr.*
      - name: Build firmware
        working-directory: ${{ env.APP_NAME }}
        run: |
          west build -b particle_xenon --pristine app
      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ${{ env.APP_NAME }}/build/zephyr/zephyr.*
